# Dependencies
markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Les Sph√®res de Sar
tagline:          'A Jekyll dqzdqzdqzdzqdqzdq'
description:      ''
url:              http://spheresdesar.github.io/shortstories/
baseurl:          /

paginate: 1

excerpt_separator: <!--more-->

gems: 
 - jekyll-paginate
 - redcarpet